[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "rub-pysimplesoap"
version = "1.16"

[tool.setuptools]
py-modules = ['pysimplesoap']
