[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pysimplesoap"
dynamic = ["version"]

[tool.setuptools]
py-modules = ['pysimplesoap']

[tool.setuptools_scm]
local_scheme = "no-local-version"
